### ISSUE TITLE
Question on Using Different Multiple Templates/Views on a Single Page Application

### ISSUE THREAD

**Issue by 1manStartup** [BoilerplateMVC/Backbone-Require-Boilerplate#16]
Just downloaded BRB today and it works great with one view as on the example. 
I was wondering how to get it to work with multiple different modular views/templates like the example page (http://gregfranko.com/Backbone-Require-Boilerplate/). I saw the the wiki and the introduction video, but haven't been able to figure it out. I'm thinking that if multiple templates is supported, it might be nice to add it to the wiki.  I appreciate any help. Thanks. 

For example I can get the same view with the same template to work twice, such as:
![backbone-req-views](https://f.cloud.github.com/assets/2334628/73279/6ac06510-6039-11e2-8b87-4d7a85ea19f9.jpg)

Here is the code of client body (index.html): 
<body>
  <div data-role="page">
    <header data-role="header" class="navbar nav navbar-inner">
       </header> 
    <div class="container-fluid" data-role="content">

```
  <div class="row-fluid">

    <div class="span3">

      <div class="example"></div>


    </div>
    <div class="span6">

      <div class="exampled2"></div>



    </div>
    <div class="span3">

      <div class="example"></div>



    </div>

  </div>

</div>


<footer class="footer navbar navbar-fixed-bottom" data-role="footer">
    <p>Written by <a href="https://github.com/gfranko" target="_blank">Greg Franko</a></p>
</footer><!-- /footer -->
```

  </div> 

</body>

I tried two things...
1) Creating two el's with the View.js generating both (example and example2)...did not work.
2) Tried creating the following files (View2.js, Model2.js, DesktopRouter2.js, etc), also no success.
Having both templates on one View.js file and creating a different version of View, Model and Controller (such as View2.js, Model2, and Controller2.js)

This is my Code for View:

// View.js
// -------
define(["jquery", "backbone", "models/Model", "models/Model2", "text!templates/heading.html", "text!templates/heading2.html"],

```
function($, Backbone, Model, Model2, template, template2){

    var View = Backbone.View.extend({

        // The DOM Element associated with this view
        el: ".example",



        // View constructor
        initialize: function() {

            // Calls the view's render method
            this.render();

        },

        // View Event Handlers
        events: {

        },

        // Renders the view's template to the UI
        render: function() {

            // Setting the view's template property using the Underscore template method
            this.template = _.template(template, {});

            // Dynamically updates the UI with the view's template
            this.$el.html(this.template);

            // Maintains chainability
            return this;

        }

    });

    //Here is View 2
```

var View2 = Backbone.View.extend({

```
        // The DOM Element associated with this view
        el: ".example2",



        // View constructor
        initialize: function() {

            // Calls the view's render method
            this.render();

        },

        // View Event Handlers
        events: {

        },

        // Renders the view's template to the UI
        render: function() {

            // Setting the view's template property using the Underscore template method
            this.template2 = _.template(template2, {});

            // Dynamically updates the UI with the view's template
            this.$el.html(this.template2);

            // Maintains chainability
            return this;

        }

    });

    // Returns the View class
    return View;
    return View2;

}
```

);

**Comment by EmreErdogan** [comment]
What about multiple templates, models, and views that have different logic? A view listens to some particular events whereas another view listens to completely different events. So, putting the event handlers in one View.js file for different templates by only switching the `el` property will grow the size of the file and this is not good for modularity, right? It's the same for models. Don't you think it would be good to put those views, models, collections, etc. into their own files? How do you handle this kind of situation? Can you please give an example?

**Comment by gfranko** [comment]
I think you can definitely put those Views, Models, and Collections into their own files.  You can also have nested child Views.  I don't have an example handy, but will add one when I do.
